@baseUrl = https://library.clausjoergensen.dk/api

@jwtToken = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGUgMiIsInN1YiI6InVzZXIxMjMiLCJleHAiOjE3MzYwMDMxODMsInJvbGVzIjoidXNlciIsInVzZXJuYW1lIjoidXNlcjEyMyJ9.BVjx4FY4ac0pFZuipJl2cmhs0tgNYTUL0gpFEiYekRw
###
GET {{baseUrl}}/books


###
POST {{baseUrl}}/auth/register/

{
    "username": "test5115",
    "password": "test5115"
}


###
POST {{baseUrl}}/auth/login/

{
    "username": "user123",
    "password": "1234"
}

###
POST {{baseUrl}}/auth/login/

{
    "username": "admin",
    "password": "admin1234"
}


###
GET {{baseUrl}}/lendbooks
Accept: application/json
Authorization: Bearer {{jwtToken}}

###
GET {{baseUrl}}/lendbooks/user
Accept: application/json
Authorization: Bearer {{jwtToken}}


###
GET {{baseUrl}}/info/user
Accept: application/json
Authorization: Bearer {{jwtToken}}