@baseUrl = https://library.clausjoergensen.dk/api

@jwtToken = "eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGUgMiIsInN1YiI6InRlc3QzMTI3IiwiZXhwIjoxNzM0MDA0OTMzLCJyb2xlcyI6InVzZXIiLCJ1c2VybmFtZSI6InRlc3QzMTI3In0.JmatFI246CrRcsrP_5-K0cFc5JTS8Hm-qMkLyCZN1BY"

###
GET {{baseUrl}}/books


###
POST {{baseUrl}}/auth/register/

{
    "username": "test3127",
    "password": "user123"
}


###
POST {{baseUrl}}/auth/login/

{
    "username": "test3127",
    "password": "user123"
}


###
GET {{baseUrl}}/lendbooks
Accept: application/json
Authorization: Bearer {{jwtToken}}


###
GET {{baseUrl}}/info/user
Accept: application/json

{
    "token": {{jwtToken}}
}